SIH/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('Web_APP.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Web_APP/urls.py
from django.urls import path 
from django.conf.urls import url
from . import views

app_name = 'Web_APP'

urlpatterns = [
    path('', views.home, name="home"),
    path('crops', views.crops, name="crops"),
    path('disease', views.disease, name="disease"),
    path('crop_result', views.crop_result, name="crop_result"),

    url(r'^wheat_disease/$', views.WheatDView.as_view(), name='wheat'),
    url(r'^wheat_disease/(?P<slug>[A-Za-z0-9_-]+)/$', views.WheatView.as_view(), name='wheat_disease'),

    url(r'^rice_disease/$', views.RiceDView.as_view(), name='rice'),
    url(r'^rice_disease/(?P<slug>[A-Za-z0-9_-]+)/$', views.RiceView.as_view(), name='rice_disease'),

    url(r'^potato_disease/$', views.PotatoDView.as_view(), name='potato'),
    url(r'^potato_disease/(?P<slug>[A-Za-z0-9_-]+)/$', views.PotatoView.as_view(), name='potato_disease'),


    url(r'^groundnut_disease/$', views.GroundnutDView.as_view(), name='groundnut'),
    url(r'^groundnut_disease/(?P<slug>[A-Za-z0-9_-]+)/$', views.GroundnutView.as_view(), name='groundnut_disease'),


    url(r'^pulses_disease/$', views.PulsesDView.as_view(), name='pulses'),
    url(r'^pulses_disease/(?P<slug>[A-Za-z0-9_-]+)/$', views.PulsesView.as_view(), name='pulses_disease'),


    url(r'^tomato_disease/$', views.TomatoDView.as_view(), name='tomato'),
    url(r'^tomato_disease/(?P<slug>[A-Za-z0-9_-]+)/$', views.TomatoView.as_view(), name='tomato_disease'),



    
]

Web_APP/models.py
from django.db import models

# Create your models here.
class Wheat_Disease(models.Model):
    name  = models.CharField(max_length=100, null=True)
    image = models.ImageField(null=True, blank=True)
    desc = models.TextField(max_length=3000, null=True)
    rem = models.TextField(max_length=3000, null=True)
    slug = models.CharField(max_length=48)

    def __str__(self):
        return self.name

    @property
    def imageURL(self):
        try:
            url = self.image.url
        except:
            url = ''
        return url


class Rice_Disease(models.Model):
    name  = models.CharField(max_length=100, null=True)
    image = models.ImageField(null=True, blank=True)
    desc = models.TextField(max_length=3000, null=True)
    rem = models.TextField(max_length=3000, null=True)
    slug = models.CharField(max_length=48)

    def __str__(self):
        return self.name

    @property
    def imageURL(self):
        try:
            url = self.image.url
        except:
            url = ''
        return url


class Potato_Disease(models.Model):
    name  = models.CharField(max_length=100, null=True)
    image = models.ImageField(null=True, blank=True)
    desc = models.TextField(max_length=3000, null=True)
    rem = models.TextField(max_length=3000, null=True)
    slug = models.CharField(max_length=48)

    def __str__(self):
        return self.name

    @property
    def imageURL(self):
        try:
            url = self.image.url
        except:
            url = ''
        return url


class Groundnut_Disease(models.Model):
    name  = models.CharField(max_length=100, null=True)
    image = models.ImageField(null=True, blank=True)
    desc = models.TextField(max_length=3000, null=True)
    rem = models.TextField(max_length=3000, null=True)
    slug = models.CharField(max_length=48)

    def __str__(self):
        return self.name

    @property
    def imageURL(self):
        try:
            url = self.image.url
        except:
            url = ''
        return url


class Pulses_Disease(models.Model):
    name  = models.CharField(max_length=100, null=True)
    image = models.ImageField(null=True, blank=True)
    desc = models.TextField(max_length=3000, null=True)
    rem = models.TextField(max_length=3000, null=True)
    slug = models.CharField(max_length=48)

    def __str__(self):
        return self.name

    @property
    def imageURL(self):
        try:
            url = self.image.url
        except:
            url = ''
        return url


class Tomato_Disease(models.Model):
    name  = models.CharField(max_length=100, null=True)
    image = models.ImageField(null=True, blank=True)
    desc = models.TextField(max_length=3000, null=True)
    rem = models.TextField(max_length=3000, null=True)
    slug = models.CharField(max_length=48)

    def __str__(self):
        return self.name

    @property
    def imageURL(self):
        try:
            url = self.image.url
        except:
            url = ''
        return url

class ContactUS(models.Model):
    name  = models.CharField(max_length=100, null=True)
    number = models.IntegerField()
    subject  = models.CharField(max_length=100, null=True)
    message  = models.CharField(max_length=100, null=True)

    def __str__(self):
        return self.subject

Web_APP/views.py
from django.shortcuts import render
from django.views.generic import ListView, DetailView
from .models import *
import joblib
from django.contrib import messages
# Create your views here.

def home(request):
    if request.method == "POST":
        name = request.POST.get('name')
        number = request.POST.get('number')
        subject = request.POST.get('subject')
        message = request.POST.get('message')

        home = ContactUS(name=name, number=number, subject=subject, message=message,) 

        home.save()
        messages.success(request, 'Your form has been submitted!')
    return render(request, 'Web_App/index.html')

def crops(request):
    return render(request, 'Web_App/crops.html')

def disease(request):
    return render(request, 'Web_App/disease.html')



def crop_result(request):

    cls = joblib.load('finalized_model.sav')

    lis = []

    lis.append(request.GET['NITROGEN'])
    lis.append(request.GET['PHOSPHORUS'])
    lis.append(request.GET['POTASSIUM'])
    lis.append(request.GET['TEMPERATURE'])
    lis.append(request.GET['HUMIDITY'])
    lis.append(request.GET['PH'])
    lis.append(request.GET['RAINFALL'])

    ans = cls.predict([lis])


    return render(request, 'Web_App/crop_result.html', {'ans':ans})

class WheatDView(ListView):
    model = Wheat_Disease
class WheatView(DetailView):
    model = Wheat_Disease


class RiceDView(ListView):
    model = Rice_Disease
class RiceView(DetailView):
    model = Rice_Disease


class PotatoDView(ListView):
    model = Potato_Disease
class PotatoView(DetailView):
    model = Potato_Disease


class GroundnutDView(ListView):
    model = Groundnut_Disease
class GroundnutView(DetailView):
    model = Groundnut_Disease


class PulsesDView(ListView):
    model = Pulses_Disease
class PulsesView(DetailView):
    model = Pulses_Disease


class TomatoDView(ListView):
    model = Tomato_Disease
class TomatoView(DetailView):
    model = Tomato_Disease

Web_APP/templates/Web_App/disease.html
<!DOCTYPE html>
{% load static %}
<html lang="en">

  <head>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="Template Mo">
    <link href="https://fonts.googleapis.com/css?family=Poppins:100,200,300,400,500,600,700,800,900" rel="stylesheet">

    <title>Farmer's Portal -Crops</title>

    <!-- Bootstrap core CSS -->
    <link href="{% static 'vendor/bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">

    <!-- Additional CSS Files -->
    <link rel="stylesheet" href="{% static 'CSS/fontawesome.css' %}">
    <link rel="stylesheet" href="{% static 'CSS/templatemo-edu-meeting.css' %}">
    <link rel="stylesheet" href="{% static 'CSS/owl.css' %}">
    <link rel="stylesheet" href="{% static 'CSS/lightbox.css' %}">


  </head>

<body>

 <div class="sub-header">
  <div class="container">
    <div class="row">
      <div class="col-lg-8 col-sm-8">
        <div class="left-content">
          <div id="google_translate_element"></div>
        </div>
      </div>
      <div class="col-lg-4 col-sm-4">
        <div class="right-icons">
          <ul>
            <li><a href="#"><i class="fa fa-facebook"></i></a></li>
            <li><a href="#"><i class="fa fa-twitter"></i></a></li>
            <li><a href="#"><i class="fa fa-behance"></i></a></li>
            <li><a href="#"><i class="fa fa-linkedin"></i></a></li>
          </ul>
        </div>
      </div>
    </div>
  </div>
</div>
<!--<div id="google_translate_element"></div>-->

<!-- * Header Area Start * -->
<header class="header-area header-sticky">
  <div class="container">
      <div class="row">
          <div class="col-12">
              <nav class="main-nav">
                  <!-- ***** Logo Start ***** -->
                  <a href="" class="logo">
                      Farmer's Portal
                  </a>
                  <!-- ***** Logo End ***** -->
                  <!-- ***** Menu Start ***** -->
                  <ul class="nav">
                      <li><a href="{% url 'Web_APP:home' %}" class="active">Home</a></li>
                      <li class="has-sub">
                          <a href="javascript:void(0)">Information</a>
                          <ul class="sub-menu">
                              <li><a href="{% url 'Web_APP:crops' %}">Crops</a></li>
                              <li><a href="{% url 'Web_APP:crops' %}">Seeds</a></li>
                              <li><a href="{% url 'Web_APP:crops' %}">Tools/Instruments</a></li>
                          </ul>
                      </li>
                      <li class="scroll-to-section"><a href="#courses">Blog</a></li> 
                      <li class="scroll-to-section"><a href="#contact">Contact Us</a></li> 
                  </ul>        
                  <a class='menu-trigger'>
                      <span>Menu</span>
                  </a>
                  <!-- ***** Menu End ***** -->
              </nav>
          </div>
      </div>
  </div>
</header>
  <!-- * Header Area End * -->

  <!--<section class="heading-page header-text" id="top">
    <div class="container">
      <div class="row">
        <div class="col-lg-12">
          <h6>Here is some information about</h6>
          <h2>Crops</h2>
        </div>
      </div>
    </div>
  </section>-->

  <section class="meetings-page" id="meetings">
    <div class="container">
      <div class="row">
        <div class="col-lg-12">
          <div class="row">
           <div class="section-heading">
            <h2 style="text-align: center;">Some Common Plant Diseases</h2>
          </div>
         </div>
        </div>
        <div class="col-lg-12">
          <div class="row grid">
            <div class="col-lg-4 templatemo-item-col all soon">
              <div class="meeting-item">
                <div class="thumb">
                  <a href=""><img src="{% static 'images/images.jpg'%}" alt="" style="height:200px"></a>
                </div>
                <div class="down-content">
                  <a href="{% url 'Web_APP:wheat' %}"><h4>Diseases of Wheat</h4></a>
                </div>
              </div>
            </div>
            <div class="col-lg-4 templatemo-item-col all soon">
              <div class="meeting-item">
                <div class="thumb">
                  <a href=""><img src="{% static 'images1/rice.jpg'%}" alt="" style="height:200px"></a>
                </div>
                <div class="down-content">
                  <a href="{% url 'Web_APP:rice' %}"><h4>Diseases of Rice</h4></a>
                </div>
              </div>
            </div>
            <div class="col-lg-4 templatemo-item-col all soon">
              <div class="meeting-item">
                <div class="thumb">
                  <a href=""><img src="{% static 'images1/potato.jpg'%}" alt="" style="height:200px"></a>
                </div>
                <div class="down-content">
                  <a href="{% url 'Web_APP:potato' %}"><h4>Diseases of Potato</h4></a>
                </div>
              </div>
            </div>
          </div>
          <div class="row grid">
            <div class="col-lg-4 templatemo-item-col all soon">
              <div class="meeting-item">
                <div class="thumb">
                  <a href=""><img src="{% static 'images1/peanut.jpg'%}" alt="" style="height:200px"></a>
                </div>
                <div class="down-content">
                  <a href="{% url 'Web_APP:groundnut' %}"><h4>Diseases of Groundnut</h4></a>
                </div>
              </div>
            </div>
            <div class="col-lg-4 templatemo-item-col all soon">
              <div class="meeting-item">
                <div class="thumb">
                  <a href=""><img src="{% static 'images1/pulses.jpg'%}" alt="" style="height:200px"></a>
                </div>
                <div class="down-content">
                  <a href="#"><h4>Diseases of Pulses</h4></a>
                </div>
              </div>
            </div>

            <div class="col-lg-4 templatemo-item-col all soon">
              <div class="meeting-item">
                <div class="thumb">
                  <a href=""><img src="{% static 'images1/tomato.jpeg'%}" alt="" style="height:200px"></a>
                </div>
                <div class="down-content">
                  <a href="{% url 'Web_APP:tomato' %}"><h4>Diseases of Tomato</h4></a>
                </div>
              </div>
            </div>

          </div>
        </div>
          </div>
        </div>
    <div class="footer">
     <p>Copyright © 2022 Farm Aid.Co, Ltd. All Rights Reserved. 
         <br>
         Designed By: CodeMates
       </p>
   </div>
  </section>


  <!-- Scripts -->
  <!-- Bootstrap core JavaScript -->
  <script src="{% static 'vendor/jquery/jquery.min.js' %}"></script>
  <script src="{% static 'vendor/bootstrap/js/bootstrap.bundle.min.js' %}"></script>

  <script src="{% static 'js/isotope.min.js' %}"></script>
  <script src="{% static 'js/owl-carousel.js' %}"></script>
  <script src="{% static 'js/lightbox.js' %}"></script>
  <script src="{% static 'js/tabs.js' %}"></script>
  <script src="{% static 'js/video.js' %}"></script>
  <script src="{% static 'js/slick-slider.js' %}"></script>
  <script src="{% static 'js/custom.js' %}"></script>


    <script>
        //according to loftblog tut
        $('.nav li:first').addClass('active');

        var showSection = function showSection(section, isAnimate) {
          var
          direction = section.replace(/#/, ''),
          reqSection = $('.section').filter('[data-section="' + direction + '"]'),
          reqSectionPos = reqSection.offset().top - 0;

          if (isAnimate) {
            $('body, html').animate({
              scrollTop: reqSectionPos },
            800);
          } else {
            $('body, html').scrollTop(reqSectionPos);
          }

        };

        var checkSection = function checkSection() {
          $('.section').each(function () {
            var
            $this = $(this),
            topEdge = $this.offset().top - 80,
            bottomEdge = topEdge + $this.height(),
            wScroll = $(window).scrollTop();
            if (topEdge < wScroll && bottomEdge > wScroll) {
              var
              currentId = $this.data('section'),
              reqLink = $('a').filter('[href*=\\#' + currentId + ']');
              reqLink.closest('li').addClass('active').
              siblings().removeClass('active');
            }
          });
        };

        $('.main-menu, .responsive-menu, .scroll-to-section').on('click', 'a', function (e) {
          e.preventDefault();
          showSection($(this).attr('href'), true);
        });

        $(window).scroll(function () {
          checkSection();
        });
    </script>
     <script type="text/javascript">
      function googleTranslateElementInit() {
        new google.translate.TranslateElement({pageLanguage: 'en'}, 'google_translate_element');
      }
      </script>
      
      <script type="text/javascript" src="//translate.google.com/translate_a/element.js?cb=googleTranslateElementInit"></script>

  </body>

</html>

Web_APP/templates/Web_App/rice_disease_detail.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
    <head>

        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
        <meta name="description" content="">
        <meta name="author" content="Template Mo">
        <link href="https://fonts.googleapis.com/css?family=Poppins:100,200,300,400,500,600,700,800,900" rel="stylesheet">
    
        <title>Farmer's Portal -Crops</title>
    
        <!-- Bootstrap core CSS -->
        <link href="{% static 'vendor/bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">
    
        <!-- Additional CSS Files -->
        <link rel="stylesheet" href="{% static 'CSS/fontawesome.css' %}">
        <link rel="stylesheet" href="{% static 'CSS/templatemo-edu-meeting.css' %}">
        <link rel="stylesheet" href="{% static 'CSS/owl.css' %}">
        <link rel="stylesheet" href="{% static 'CSS/lightbox.css' %}">
    
    
      </head>
<body>
        <div class="sub-header">
          <div class="container">
            <div class="row">
              <div class="col-lg-8 col-sm-8">
                <div class="left-content">
                  <div id="google_translate_element"></div>
                </div>
              </div>
      
            </div>
          </div>
        </div>
        <!--<div id="google_translate_element"></div>-->
        
        <!-- ***** Header Area Start ***** -->
        <header class="header-area header-sticky">
            <div class="container">
                <div class="row">
                    <div class="col-12">
                        <nav class="main-nav">
                            <!-- ***** Logo Start ***** -->
                            <a href="index.html" class="logo">
                                Farmer's Portal
                            </a>
                            <!-- ***** Logo End ***** -->
                            <!-- ***** Menu Start ***** -->
                            <ul class="nav">
                                <li ><a href="{% url 'Web_APP:home' %}" class="active">Home</a></li>
                                <li class="has-sub">
                                    <a href="javascript:void(0)">Information</a>
                                    <ul class="sub-menu">
                                        <li><a href="{% url 'Web_APP:crops' %}">Crops</a></li>                                  
                                        <li><a href="{% url 'Web_APP:disease' %}">Diseases</a></li>
                                        <li><a href="{% url 'Web_APP:crops' %}">Seeds</a></li>
                                    </ul>
                                </li>
                                <li class="scroll-to-section"><a href="#courses">Blog</a></li> 
                                <li class="scroll-to-section"><a href="#contact">Contact Us</a></li> 
                            </ul>        
                            <a class='menu-trigger'>
                                <span>Menu</span>
                            </a>
                            <!-- ***** Menu End ***** -->
                        </nav>
                    </div>
                </div>
            </div>
        </header>
        <!-- ***** Header Area End ***** -->
      
        <section class="meetings-page" id="meetings">
          <div class="container">
                <div class="row">
                  <div class="col-lg-12">
                    <div class="meeting-single-item">
                      <div class="thumb">
                        <img class="thumbnail"  src="{{ rice_disease.imageURL }}" style="height: 400px;"  ></a>
                      </div>
                      <br>
                      <div class="down-content">
                        <h1 style="text-align: center;" > {{ rice_disease.name }}</h1>
                        <p class="description">{{ rice_disease.desc }}
                        </p>
                        <div class="row">
                          <div class="col-lg-4">
                            <div class="hours">
                              <h5>Remidies</h5>
                              <p>{{ rice_disease.rem }}</p>
                            </div>
                          </div>
                        </div>
                      </div>
                    </div>
                  </div>
                  </div>
            </div>
          </div>
          <div class="footer">
           <p>Copyright © 2022 Farmer's Portal.Co, Ltd. All Rights Reserved. 
               <br>
               Designed By: CodeMates
             </p>
         </div>
        </section>
      
      
        <!-- Scripts -->
        <!-- Bootstrap core JavaScript -->
          <script src="vendor/jquery/jquery.min.js"></script>
          <script src="vendor/bootstrap/js/bootstrap.bundle.min.js"></script>
      
          <script src="assets/js/isotope.min.js"></script>
          <script src="assets/js/owl-carousel.js"></script>
          <script src="assets/js/lightbox.js"></script>
          <script src="assets/js/tabs.js"></script>
          <script src="assets/js/video.js"></script>
          <script src="assets/js/slick-slider.js"></script>
          <script src="assets/js/custom.js"></script>
          <script>
              //according to loftblog tut
              $('.nav li:first').addClass('active');
      
              var showSection = function showSection(section, isAnimate) {
                var
                direction = section.replace(/#/, ''),
                reqSection = $('.section').filter('[data-section="' + direction + '"]'),
                reqSectionPos = reqSection.offset().top - 0;
      
                if (isAnimate) {
                  $('body, html').animate({
                    scrollTop: reqSectionPos },
                  800);
                } else {
                  $('body, html').scrollTop(reqSectionPos);
                }
      
              };
      
              var checkSection = function checkSection() {
                $('.section').each(function () {
                  var
                  $this = $(this),
                  topEdge = $this.offset().top - 80,
                  bottomEdge = topEdge + $this.height(),
                  wScroll = $(window).scrollTop();
                  if (topEdge < wScroll && bottomEdge > wScroll) {
                    var
                    currentId = $this.data('section'),
                    reqLink = $('a').filter('[href*=\\#' + currentId + ']');
                    reqLink.closest('li').addClass('active').
                    siblings().removeClass('active');
                  }
                });
              };
      
              $('.main-menu, .responsive-menu, .scroll-to-section').on('click', 'a', function (e) {
                e.preventDefault();
                showSection($(this).attr('href'), true);
              });
      
              $(window).scroll(function () {
                checkSection();
              });
          </script>
          <script type="text/javascript">
           function googleTranslateElementInit() {
             new google.translate.TranslateElement({pageLanguage: 'en'}, 'google_translate_element');
           }
           </script>
           
           <script type="text/javascript" src="//translate.google.com/translate_a/element.js?cb=googleTranslateElementInit"></script>
      

</body>
</html>

Web_APP/templates/Web_App/rice_disease_list.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <!DOCTYPE html>
{% load static %}
<html lang="en">

  <head>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="Template Mo">
    <link href="https://fonts.googleapis.com/css?family=Poppins:100,200,300,400,500,600,700,800,900" rel="stylesheet">

    <title>Farmer's Portal -Crops</title>

    <!-- Bootstrap core CSS -->
    <link href="{% static 'vendor/bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">

    <!-- Additional CSS Files -->
    <link rel="stylesheet" href="{% static 'CSS/fontawesome.css' %}">
    <link rel="stylesheet" href="{% static 'CSS/templatemo-edu-meeting.css' %}">
    <link rel="stylesheet" href="{% static 'CSS/owl.css' %}">
    <link rel="stylesheet" href="{% static 'CSS/lightbox.css' %}">


  </head>

<body>

 <div class="sub-header">
  <div class="container">
    <div class="row">
      <div class="col-lg-8 col-sm-8">
        <div class="left-content">
          <div id="google_translate_element"></div>
        </div>
      </div>
      <div class="col-lg-4 col-sm-4">
        <div class="right-icons">
          <ul>
            <li><a href="#"><i class="fa fa-facebook"></i></a></li>
            <li><a href="#"><i class="fa fa-twitter"></i></a></li>
            <li><a href="#"><i class="fa fa-behance"></i></a></li>
            <li><a href="#"><i class="fa fa-linkedin"></i></a></li>
          </ul>
        </div>
      </div>
    </div>
  </div>
</div>
<!--<div id="google_translate_element"></div>-->
<header class="header-area header-sticky">
    <div class="container">
        <div class="row">
            <div class="col-12">
                <nav class="main-nav">
                    <!-- ***** Logo Start ***** -->
                    <a href="" class="logo">
                        Farmer's Portal
                    </a>
                    <!-- ***** Logo End ***** -->
                    <!-- ***** Menu Start ***** -->
                    <ul class="nav">
                        <li ><a href="{% url 'Web_APP:home' %}" class="active">Home</a></li>
                        <li class="has-sub">
                            <a href="javascript:void(0)">Information</a>
                            <ul class="sub-menu">
                                <li><a href="{% url 'Web_APP:crops' %}">Crops</a></li>                                  
                                <li><a href="{% url 'Web_APP:disease' %}">Diseases</a></li>
                                <li><a href="{% url 'Web_APP:crops' %}">Seeds</a></li>
                            </ul>
                        </li>
                        <li class="scroll-to-section"><a href="#courses">Blog</a></li> 
                        <li class="scroll-to-section"><a href="#contact">Contact Us</a></li> 
                    </ul>        
                    <a class='menu-trigger'>
                        <span>Menu</span>
                    </a>
                    <!-- ***** Menu End ***** -->
                </nav>
            </div>
        </div>
    </div>
</header>
<!-- * Header Area Start * -->

  <!-- * Header Area End * -->

  <!--<section class="heading-page header-text" id="top">
    <div class="container">
      <div class="row">
        <div class="col-lg-12">
          <h6>Here is some information about</h6>
          <h2>Crops</h2>
        </div>
      </div>
    </div>
  </section>-->

  <section class="meetings-page" id="meetings">
    <div class="container">
      <div class="row">
        <div class="col-lg-12">
          <div class="row">
           <div class="section-heading">
            <h2 style="text-align: center;">Some Types Of Rice Diseases</h2>
          </div>
         </div>
        </div>
        <div class="col-lg-12">
            
          <div class="row grid">
            {% for rice_disease in rice_disease_list %}
            <div class="col-lg-4 templatemo-item-col all soon">
              <div class="meeting-item">
                <div class="thumb">
                  <a href=""><img class="thumbnail" src="{{ rice_disease.imageURL }}" style="height:200px"></a>
                  &ndash; 
                </div>
                <div class="down-content">
                    <a href="{% url 'Web_APP:rice_disease' rice_disease.slug %}"><h4>
                        {{ rice_disease.name }}
                    </h4></a>
                </div>
              </div>
            </div>
            {% endfor %}
          </div>
        </div>
    <div class="footer">
     <p>Copyright © 2022 Farm Aid.Co, Ltd. All Rights Reserved. 
         <br>
         Designed By: CodeMates
       </p>
   </div>
  </section>


  <!-- Scripts -->
  <!-- Bootstrap core JavaScript -->
  <script src="{% static 'vendor/jquery/jquery.min.js' %}"></script>
  <script src="{% static 'vendor/bootstrap/js/bootstrap.bundle.min.js' %}"></script>

  <script src="{% static 'js/isotope.min.js' %}"></script>
  <script src="{% static 'js/owl-carousel.js' %}"></script>
  <script src="{% static 'js/lightbox.js' %}"></script>
  <script src="{% static 'js/tabs.js' %}"></script>
  <script src="{% static 'js/video.js' %}"></script>
  <script src="{% static 'js/slick-slider.js' %}"></script>
  <script src="{% static 'js/custom.js' %}"></script>


    <script>
        //according to loftblog tut
        $('.nav li:first').addClass('active');

        var showSection = function showSection(section, isAnimate) {
          var
          direction = section.replace(/#/, ''),
          reqSection = $('.section').filter('[data-section="' + direction + '"]'),
          reqSectionPos = reqSection.offset().top - 0;

          if (isAnimate) {
            $('body, html').animate({
              scrollTop: reqSectionPos },
            800);
          } else {
            $('body, html').scrollTop(reqSectionPos);
          }

        };

        var checkSection = function checkSection() {
          $('.section').each(function () {
            var
            $this = $(this),
            topEdge = $this.offset().top - 80,
            bottomEdge = topEdge + $this.height(),
            wScroll = $(window).scrollTop();
            if (topEdge < wScroll && bottomEdge > wScroll) {
              var
              currentId = $this.data('section'),
              reqLink = $('a').filter('[href*=\\#' + currentId + ']');
              reqLink.closest('li').addClass('active').
              siblings().removeClass('active');
            }
          });
        };

        $('.main-menu, .responsive-menu, .scroll-to-section').on('click', 'a', function (e) {
          e.preventDefault();
          showSection($(this).attr('href'), true);
        });

        $(window).scroll(function () {
          checkSection();
        });
    </script>
     <script type="text/javascript">
      function googleTranslateElementInit() {
        new google.translate.TranslateElement({pageLanguage: 'en'}, 'google_translate_element');
      }
      </script>
      
      <script type="text/javascript" src="//translate.google.com/translate_a/element.js?cb=googleTranslateElementInit"></script>

  </body>

</html>
<!--


    {% for wheat_disease in wheat_disease_list %}
    <ul>
        <li><a href="{% url 'Web_APP:wheat_disease' wheat_disease.slug %}">{{ wheat_disease.name }}</a>
            &ndash; 
            <img class="thumbnail" style="height: 8cm; width: 8cm; " src="{{ wheat_disease.imageURL }}">
    </ul>
    {% endfor %}
</body>
</html>-->